nhorman/dropwatch

configure.ac
src/Makefile.am

Use pkg-config to get readline dependencies such as ncurses
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

fix static build with readline

---

src/lookup_kas.c

In 32bit big endian platform, memcpy a 32bit pointer to u64 will get
a bad result.
Signed-off-by: xiaofan <xfan1024@live.com>

fix cast bug in big endian platform

---

src/lookup.c
src/lookup_bfd.c
src/lookup_kas.c

libbfd from binutils 2.23.1+ requires PACKAGE* definitions from autoconf.
Patch from https://fedorahosted.org/dropwatch/ticket/5
Upstream status: new.
Signed-off-by: Gustavo Zacarias <gustavo@zacarias.com.ar>
[Retrieved from:
https://git.buildroot.net/buildroot/tree/package/dropwatch/0001-binutils-2.23.1.patch]
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

Fix for binutils 2.23.1

---

configure.ac
src/Makefile.am
src/lookup.c
src/lookup.h
src/lookup_kas.c

Add an option to enable or disable bfd support to allow the user to use
dropwatch without binutils
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

Make binutils optional

---

README.md
doc/dropwatch.1
spec/dropwatch.spec
src/lookup.c
src/lookup.h
src/lookup_bfd.c
src/lookup_kas.c
src/main.c
src/net_dropmon.h
tests/Makefile.am
tests/rundropwatch.sh

Hi,
The drop monitor kernel module was recently extended with two new features which are expected to be merged to the 5.4 kernel. This pull request adds support for these new features in DropWatch.
The first feature was merged in [this](https://git.kernel.org/pub/scm/linux/kernel/git/davem/net-next.git/commit/?id=6e5ee483397aa02e5656191cb9f59e4095b4d249) kernel merge commit. It extends drop monitor with another alert mode in which dropped packets are notified to user space, instead of just a summary of recent drops. This enables users to perform a more detailed analysis of the dropped packets. Please refer to the kernel merge commit for example usage as well as to the individual commit messages in this pull request. The man page and help command were extended as well.
The second feature …

Add packet alert mode and monitoring of hardware originated drops

---

configure.ac
doc/dwdump.1
src/Makefile.am
src/dwdump.c

Since kernel 5.4 it is possible to instruct the drop monitor kernel
module to generate netlink events that contain the payload of dropped
packets. These netlink packets can be dissected by the Wireshark drop
monitor dissector since Wireshark version 3.1.1
Currently, the only way to consume these packets is by running DropWatch
and having Wireshark listen on the nlmon netdev.
Instead, this patch adds a new utility that can directly dump these
packets to a file in pcap format.
Examples (from the man page)
============================
1. Dump dropped packets to a file:
dwdump -w drops.pcap
2. Pipe dropped packets to Wireshark:
dwdump | tshark -V -r -
3. Only monitor software originated drops:
dwdump -o sw -w drops.pcap
4. Query current configuration from the kernel and exit:
dwdump -q
Future …

Add dwdump utility to dump kernel dropped packets to a file

---

.travis.yml

The recently added dwdump utility depends on libpcap. Add libpcap-dev as
a dependency in travis configuration file.
Fixes: 199440959a28 ("Add dwdump utility to dump kernel dropped packets to a file")
Signed-off-by: Ido Schimmel <idosch@mellanox.com>

Add libpcap-dev to CI

---

src/main.c
src/net_dropmon.h

If cookie is passed along, print it out in packet alert mode.
Example:
dropwatch> set hw true
setting hardware drops monitoring to 1
dropwatch> set alertmode packet
Setting alert mode
Alert mode successfully set
dropwatch> start
Enabling monitoring...
Kernel monitoring activated.
Issue Ctrl-C to stop monitoring
drop at: ingress_flow_action_drop (acl_drops)
origin: hardware
input port ifindex: 30
input port name: enp0s16np1
cookie: 31237981273918  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
timestamp: Thu Jan 23 12:58:56 2020 434291226 nsec
protocol: 0x800
length: 98
original length: 98

Implement cookie printout in packet alert mode

---

.travis.yml
configure.ac

libpcap in ubuntu is missing its .pc file, so autoconf fails.  They are
fixing it in newer releases but won't fix it in trusty, so lets home
updating the ci environment to xneial will get us an updated libpcap
package
Signed-off-by: Neil Horman <nhorman@tuxdriver.com>

Update distro to Xenial in the hopes that ubuntu will fix libpcap

---

src/dwdump.c

libnl commit b4802a17a765 ("nl: add "const" specifier for nla_policy
argument of parse functions") added 'const' qualifier to 'struct
nla_policy *' argument of the various *_parse() functions.
However, this commit is only present in libnl-3.5, whereas some
distributions are still shipping older versions.
This results in compilation errors such as:
```
dwdump.c:219:8: error: passing argument 5 of ‘genlmsg_parse’ discards
‘const’ qualifier from pointer target type
[-Werror=discarded-qualifiers]
```
Fix this by removing 'const' qualifier from the netlink attributes
policy structures in dwdump utility source. This is consistent with main
dropwatch utility source.
Fixes: 199440959a28 ("Add dwdump utility to dump kernel dropped packets to a file")
Signed-off-by: Ido Schimmel …

Fix compilation error with old libnl

---

src/dwdump.c

libpcap commit 98e570c4d970 ("Make the second argument to pcap_perror()
const.") added 'const' qualifier to the second argument of
pcap_perror().
However, this commit is only present in libpcap-1.8, whereas some
distributions are still shipping older versions.
This results in compilation errors such as:
```
dwdump.c:520:36: error: passing argument 2 of ‘pcap_perror’ discards
‘const’ qualifier from pointer target type
[-Werror=discarded-qualifiers]
```
Fix this by passing the name of the function that failed - as we do with
perror() - instead of passing the name of the dump file that
pcap_dump_open() failed to open.
Fixes: 199440959a28 ("Add dwdump utility to dump kernel dropped packets to a file")
Signed-off-by: Ido Schimmel <idosch@mellanox.com>

Fix compilation error with old libpcap

---

src/dwdump.c
src/main.c

Because -Werror is set, some printf statements caused build errors on
32-bit systems when printing uint64_t. This can be handled in a portable
way by using the macros from inttypes.h …
Fixes: #12
Signed-off-by: Alexander Dahl <post@lespocky.de>

Fix build on 32-bit systems

---

src/main.c

Passing a char buffer cast to struct nlmsghdr * violates the rules of
-Wcast-align on some arches, as described in :
https://github.com/nhorman/dropwatch/issues/26
Fix it by declaring the buffer as a struct nlmsghdr, and casting to a
less alligned type
Signed-off-by: Neil Horman <nhorman@tuxdriver.com>
resolves https://github.com/nhorman/dropwatch/issues/26

Fix build issue when compiling with -Wcast-align

---

configure.ac
src/Makefile.am

Apparently, way back when we wrote the configure script, we included a
package check for libnl, but not libnl3-genl (ostensibly because it
didn't exist I think), and so we hardcoded linking to -lnl3-genl.  The
pkg-config file for that library exists now, so lets actually test for
it during the running of configure, and use its output during make
Signed-off-by: Neil Horman <nhorman@tuxdriver.com>

Fix configure for libnl3-genl

---

src/lookup_kas.c

Theres a problem with how we are managing EOF and error conditions in
kas scanning. Catch the error conditions properly and exit accordingly
Signed-off-by: Neil Horman <nhorman@tuxdriver.com>

Fix fscanf error handling

---

src/lookup_bfd.c

Fix following compilation error:
lookup_bfd.c: In function ‘lookup_bfd_init’:
lookup_bfd.c:39:54: error: ‘sprintf’ may write a terminating nul past the end of the destination [-Werror=format-overflow=]
39 |         sprintf(dbibuf,"/usr/lib/debug/lib/modules/%s", uts.release);
|                                                      ^
lookup_bfd.c:39:9: note: ‘sprintf’ output between 28 and 287 bytes into a destination of size 286
39 |         sprintf(dbibuf,"/usr/lib/debug/lib/modules/%s", uts.release);
|         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Signed-off-by: Ido Schimmel <idosch@nvidia.com>

Fix compilation error with gcc 11

---

src/net_dropmon.h

when compile with glibc < 2.24 that doesn't support SOL_NETLINK it will
cause compilation failure:
gcc -DHAVE_CONFIG_H -I. -I..  -D_GNU_SOURCE  -g -Wall -Werror -I/usr/include/libnl3 -I/usr/include/libnl3  -g -O2 -MT dwdump.o -MD -MP -MF $depbase.Tpo -c -o
dwdump.o dwdump.c &&\
mv -f $depbase.Tpo $depbase.Po
dwdump.c: In function ‘dwdump_data_init’:
dwdump.c:126:23: error: ‘SOL_NETLINK’ undeclared (first use in this function)
err = setsockopt(fd, SOL_NETLINK, NETLINK_NO_ENOBUFS, &optval,
^
dwdump.c:126:23: note: each undeclared identifier is reported only once for each function it appears in
Makefile:422: recipe for target 'dwdump.o' failed
make[2]: *** [dwdump.o] Error 1
Signed-off-by: Sun Feng <loyou85@gmail.com>

fix SOL_NETLINK undeclared error for glibc < 2.24

---

configure.ac

Hi all,
I was trying to build dropwatch using Debian libreadline-dev 7.0-5 until I ran into this `.pc` thing.  The comment in `configure.ac` confused me a bit, and I think we should just delete it?
Thanks,
Peilin Ye
---
We removed the -lreadline hack for libreadline in commit c18f3d25a94e
("Update configure to fail if readline isn't installed").  Delete the
comment for less confusion.
Signed-off-by: Peilin Ye <peilin.ye@bytedance.com>

configure.ac: Delete outdated comment about -lreadline

---

src/lookup_bfd.c

With gcc 12, there is a warning:
lookup_bfd.c: In function 'lookup_bfd_init':
lookup_bfd.c:39:52: error: '%s' directive writing up to 389 bytes into a region of size 260 [-Werror=format-overflow=]
39 |         sprintf(dbibuf,"/usr/lib/debug/lib/modules/%s", uts.release);
|                                                    ^~   ~~~~~~~~~~~
In file included from /usr/include/stdio.h:894,
from lookup_bfd.c:14:
In function 'sprintf',
inlined from 'lookup_bfd_init' at lookup_bfd.c:39:2:
/usr/include/bits/stdio2.h:38:10: note: '__sprintf_chk' output between 28 and 417 bytes into a destination of size 287
38 |   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
39 |                                   __glibc_objsize …

Fix compilation error with gcc 12

---

spec/dropwatch.spec

Let's add autoconf, automake, libtool as a build requirements
to spec file. It may be useful for users who building
dropwatch "by hands" as a reference.
I've spent some time in debugging dropwatch build problem:
```lookup_bfd.o: In function `lookup_bfd_init':
/root/dropwatch/src/lookup_bfd.c:48: undefined reference to `bfd_init'```
the reason was in absence of libtool in my system. As a result
not correct gcc invocation command was constructed by autoconf:
`gcc -g -Wall -Werror -I... -g -O2 -lnl-3   -lnl-genl-3 -l...   -lpcap -lbfd  -o dropwatch main.o lookup.o lookup_kas.o lookup_bfd.o  -lpcap`
the problem here is that we have -lbfd mentioned *before* object files, so ld
just forget about bfd symbols.
Installing libtool and regeneration of the build scripts/Makefile solves the problem. …

spec: add libtool as build requirement

---

src/Makefile.am

When libtool is not installed, automake calls the linker with the library flags (`-llib`) _before_ the object files. In order to successfully resolve symbols, the library flags need to come _after_ any object file needing them. libtool does that correctly by itself, but when automake cannot rely on libtool, we need to tell it about libraries via `mybin_LDADD` instead of the global `AM_LDFLAGS`.
Fixes #82.

Fix build without libtool

---

.github/workflows/ci.yml

Not sure what's up with your Travis build. This adds CI via GitHub actions. GH hosted runners are currently only available for x86_64. Feel free to just close the PR if you don't care about GH Actions for CI.

Add GH Actions CI config
